In [10]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append("..")

import importlib
import simulation.inclusion_probability as ip

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [11]:
importlib.reload(ip)

In [12]:
import pandas as pd
from tqdm import tqdm

In [13]:
populations = pd.read_excel('../clean_data/book_value_populations.xlsx')

In [14]:
populations

      BV_5pct_above_SI  BV_15pct_above_SI  BV_30pct_above_SI
0         5.000000e+07       5.000000e+07       5.000000e+07
1         4.500000e+07       4.500000e+07       4.500000e+07
2         4.000000e+07       4.000000e+07       4.000000e+07
3         2.487642e+07       2.198396e+07       1.828721e+07
4         2.430086e+07       2.147533e+07       1.786411e+07
...                ...                ...                ...
5025      4.735788e+03       4.185144e+03       3.481383e+03
5026      4.245868e+03       3.752188e+03       3.121232e+03
5027      3.620519e+03       3.199551e+03       2.661524e+03
5028      2.970595e+03       2.625196e+03       2.183751e+03
5029      2.842883e+03       2.512333e+03       2.089867e+03

[5030 rows x 3 columns]

In [15]:
populations.columns[0].split('_')[1]

'5pct'

In [22]:
info = []
for pop in populations.columns:
    population = populations.copy()
    population.rename(columns={pop: "BV"}, inplace=True)

    population = ip.iterative_hv_selection(population, population["BV"].sum(), 100)
    info.append({
        "Population": pop.split('_')[1],
        "Total": population["BV"].sum(),
        "Average": population["BV"].mean(),
        "Median": population["BV"].median(),
        "Minimum": population["BV"].min(),
        "Maximum": population["BV"].max(),
        "Number of items above tolerable error": population['HV'].sum(),
        "Book amount of items above tolerable error": population[population['HV']==1]["BV"].sum(),
    })


population_info = pd.DataFrame.from_records(info)

In [33]:
df = population_info.T
df.columns = df.iloc[0]
df = df[1:]
df

Population,5pct,15pct,30pct
Total,3425979382.420001,3425979382.420001,3425979382.42
Average,681109.221157,681109.221157,681109.221157
Median,265633.802677,235516.95465,196020.340398
Minimum,2842.883269,2512.332969,2089.867016
Maximum,50000000.0,50000000.0,50000000.0
Number of items above tolerable error,4,13,25
Book amount of items above tolerable error,171567140.66329,550867484.886543,1048305607.483457

In [35]:
df.to_excel('../results/population_info.xlsx')