In [1]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append("..")

import importlib
import create_population.error_predictions as ep
import create_population.pop_from_eu_funds as pop

importlib.reload(ep)
importlib.reload(pop)

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('../clean_data/all_dfs_w_2526_population.xlsx')

In [4]:
real_population, metrics = ep.get_population(df, 'FEDER_FC')
real_population.head()

c:\Users\isabe\Desktop\PhD\Articles\A3. Artigo MRS standard\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

,typology_of_intervention_agg,legal_nature_beneficiary_agg,no_programs_of_operations_beneficiary_managed_cumulative_agg,op_debt_status_agg,error_binary,in_sample,high_value,year,moment,fund,code_operation,total_certified_cost,stratum,error_rate,error_monetary_value,predicted_probability
0,FEDER&FC_Grupo Outras TI,"Grupo 6 - Comerc., emp. indiv. e pessoas sing.",BF w 1 prog,N,0,0.0,0,2021_2022,1o_mom,FEDER_FC,POCI-02-08D6-FEDER-123311,5000.00,COVID,NaN,NaN,0.004079
1,FEDER&FC_Grupo Outras TI,"Grupo 6 - Comerc., emp. indiv. e pessoas sing.",BF w 1 prog,N,0,0.0,0,2021_2022,1o_mom,FEDER_FC,POCI-07-62E2-FEDER-164214,4468.72,COVID,NaN,NaN,0.004079
2,FEDER&FC_Grupo Outras TI,"Grupo 6 - Comerc., emp. indiv. e pessoas sing.",BF w 1 prog,N,0,0.0,0,2021_2022,1o_mom,FEDER_FC,POCI-02-08D6-FEDER-176217,1044.00,COVID,NaN,NaN,0.004079
3,FEDER&FC_Grupo Outras TI,"Grupo 6 - Comerc., emp. indiv. e pessoas sing.",BF w 1 prog,N,0,0.0,0,2021_2022,1o_mom,FEDER_FC,POCI-02-08D6-FEDER-163714,317.00,COVID,NaN,NaN,0.004079
4,FEDER&FC_Grupo Outras TI,"Grupo 6 - Comerc., emp. indiv. e pessoas sing.",BF w 1 prog,N,0,0.0,0,2021_2022,1o_mom,FEDER_FC,POCI-02-08D6-FEDER-159301,1023.80,COVID,NaN,NaN,0.004079

In [5]:
artificial_pop = pop.synthetic_population_eu_funds(df, 'FEDER_FC')

c:\Users\isabe\Desktop\PhD\Articles\A3. Artigo MRS standard\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

   Threshold Precision Recall for 1s Recall for 0s  F1-Score
0        0.1  0.447005      0.915094       0.72912  0.600619
1       0.15  0.479798      0.896226      0.767494     0.625
2        0.2  0.508197      0.877358       0.79684  0.643599
3       0.25   0.52381      0.830189      0.819413  0.642336
4        0.3   0.52795      0.801887      0.828442  0.636704
5       0.35  0.546053      0.783019      0.844244  0.643411
6        0.4  0.560284      0.745283      0.860045  0.639676
7       0.45  0.577778      0.735849      0.871332  0.647303
8        0.5  0.573643      0.698113      0.875847  0.629787
9       0.55  0.683333      0.386792      0.957111  0.493976
10       0.6   0.73913      0.160377      0.986456  0.263566
11      0.65  0.764706      0.122642      0.990971  0.211382
12       0.7  0.764706      0.122642      0.990971  0.211382

In [6]:
artificial_pop

                BV   ER    E         P
0         18750.00  0.0  0.0  0.004079
1         18750.00  0.0  0.0  0.004079
2         18750.00  0.0  0.0  0.004079
3         18750.00  0.0  0.0  0.004079
4         18750.00  0.0  0.0  0.004079
...            ...  ...  ...       ...
111879  5109296.33  0.0  0.0  0.002019
111880  5109296.33  0.0  0.0  0.002019
111881  5109296.33  0.0  0.0  0.002019
111882  5109296.33  0.0  0.0  0.002019
111883  5109296.33  0.0  0.0  0.002019

[111884 rows x 4 columns]

In [7]:
artificial_pop = pop.synthetic_population_eu_funds(df, 'FSE')

   Threshold Precision Recall for 1s Recall for 0s  F1-Score
0        0.1  0.645598      0.993056      0.237864   0.78249
1       0.15  0.658986      0.993056      0.281553  0.792244
2        0.2   0.67619      0.986111      0.339806   0.80226
3       0.25  0.697044      0.982639      0.402913  0.815562
4        0.3  0.728232      0.958333           0.5  0.827586
5       0.35  0.761905      0.944444      0.587379  0.843411
6        0.4  0.774566      0.930556      0.621359  0.845426
7       0.45  0.816393      0.864583      0.728155  0.839798
8        0.5  0.824138      0.829861      0.752427   0.82699
9       0.55  0.829787        0.8125       0.76699  0.821053
10       0.6  0.834559      0.788194      0.781553  0.810714
11      0.65  0.862069      0.694444       0.84466  0.769231
12       0.7  0.855856      0.659722       0.84466  0.745098

c:\Users\isabe\Desktop\PhD\Articles\A3. Artigo MRS standard\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\isabe\Desktop\PhD\Articles\A3. Artigo MRS standard\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [8]:
artificial_pop

              BV   ER    E         P
0       20116.77  0.0  0.0  0.944024
1       20116.77  0.0  0.0  0.944024
2       20116.77  0.0  0.0  0.944024
3       20116.77  0.0  0.0  0.944024
4       20116.77  0.0  0.0  0.944024
...          ...  ...  ...       ...
13887  705393.41  0.0  0.0  0.031890
13888  705393.41  0.0  0.0  0.031890
13889  705393.41  0.0  0.0  0.031890
13890  705393.41  0.0  0.0  0.031890
13891  705393.41  0.0  0.0  0.031890

[13892 rows x 4 columns]